//
// Created by regoeco on 29/11/16.
/*
    Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
                1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */
#include <stdio.h>
#include <math.h>
int main(void){
    int fib = 1, fib_ant = 1, fib_tmp = 0;
    int max = 4000000, sum = 0;

    //printf("%0.0f\n", fib_ant);
    //printf("%0.0f\n", fib);
    while(fib < max){
        printf("%d\n", fib);
        if(fib%2 == 0)
            sum+=fib;
        fib_tmp = fib;
        fib += fib_ant;
        fib_ant = fib_tmp;
    }

    printf("Sum:%d\n", sum);
    return 0;
}